### ISSUE TITLE
I can't run the program successfully

### ISSUE THREAD

**Issue by 12kobe** [Luca96/carla-driving-rl-agent#20]
Hello, I am a novice, I spent a lot of time trying to run your program again, after solving many problems, I can't solve this problem now, could you please help me to see how to solve it? Thank you very much. I really want to run this program successfully!
<img width="1280" alt="1662629014(1)" src="https://user-images.githubusercontent.com/100343829/189087121-1961428b-f5b0-4f06-accf-cbc2a138a563.png">

**Comment by Luca96** [comment]
Hi, it can be due to the version of OpenAI gym try installing version 0.22 or older.

Let me know if the issue still occurs

**Comment by 12kobe** [comment]
> 

Hello, thank you very much for your timely answer, which is very important for me as I am eager to solve the problem. Just now I checked the version of the GYM in my virtual environment, which is already 0.26.0 version. So I guess it may not be the version of GYM!
<img width="1280" alt="dierge" src="https://user-images.githubusercontent.com/100343829/189138238-27e7eb6d-2d17-4e8e-a990-04da53823089.png">

**Comment by 12kobe** [comment]
> Hi, it can be due to the version of OpenAI gym try installing version 0.22 or older.
> 
> Let me know if the issue still occurs
<img width="1280" alt="1662645041(1)" src="https://user-images.githubusercontent.com/100343829/189139908-9faba6ce-b156-49a6-9f90-cccb17c9ed07.png">
Hello, thank you very much for your timely answer, which is very important for me as I am eager to solve the problem. Just now I checked the version of the GYM in my virtual environment, which is already 0.26.0 version. So I guess it may not be the version of GYM!Can you see the picture? I don't know why uploading pictures doesn't work

**Comment by Luca96** [comment]
Yes I can see the picture, and in fact your version of gym is newer! Try installing an older one, e.g `pip install gym==0.22.0`, and see if the error is still there

**Comment by 12kobe** [comment]
> Yes I can see the picture, and in fact your version of gym is newer! Try installing an older one, e.g `pip install gym==0.22.0`, and see if the error is still there

Hello, thank you very much for your answer. I have successfully run your program. This is the first program about reinforcement learning that I have successfully reproduced. I am very happy. Thank you again! In addition, I have a few small questions to ask you. First, I find that the frame number of the picture is very low, which leads to the image of pyGame's camera being particularly blurred, and the image of Carla is also very blurred. Is there any way to make it clearer? Second, I found that Carla and pygame are lagging when running the program, and after running for a while, pyGame would not respond, and then it and Carla would crash. What is the reason and what is the solution? My computer is configured with AMD ryzen 7 5800h, rtx3060 laptop GPU and 16g running memory. Is my computer not configured enough? Third, I have learned the basics of reinforcement learning at present. I want to learn more about how reinforcement learning should be applied by learning your code. There may be a lot of things I don't understand when I study your code. I want to ask you if there are any questions at that time! I don't know if you have wechat. Can you add one conveniently? I promise not to disturb you frequently! Thank you again!

**Comment by 12kobe** [comment]
> Hi and sorry for the late response.
> 
> In general the framerate is low, at most I managed to achieve 10-15 FPS. This is mainly due to the CARLA simulator itself but also to the agent's network that has to process 3 90x120x3 camera images at each frame.
> 
> As you can see [here](https://github.com/Luca96/carla-driving-rl-agent/blob/master/core/learning.py#L58), you can set both the camera resolution and the size of the pygame window. I picked these settings for best performance over quality, also because the memory consumption is quite high (#10). Moreover, also the simulator quality is set to `low`: see the repo's README; in general, when you lunch CARLA, you should remove the argument `--quality-level=Low`, but expect slower performance. Refer to also this issue #12.
> 
> Your computer have an adeguate CPU, but both the GPU and RAM memory are a bit small. So, you have to consider to reduce the batch size and also the number of timesteps, and/or the image resolution.
> 
> For further details about the code, see these issues: #11, #8, #4, and #18.
> 
> If you want to better understand the code, you should learn the CARLA API first (https://carla.readthedocs.io/en/latest/start_quickstart/), and you should also take a reinforcement learning course ([this](https://spinningup.openai.com/en/latest/spinningup/rl_intro.html) is a good place to start.)
> 
> Lastly, if you need to contact me, please do this only via email. Thanks.

**Comment by 12kobe** [comment]
I'm sorry that I accidentally closed this question. I can only choose to use email to ask you questions. I hope you can see the email. Thank you!
