### ISSUE TITLE
Stuck with an error

### ISSUE THREAD

**Issue by Halcyon-Lexie** [Luca96/carla-driving-rl-agent#5]
When I run this demo:
learning.stage_s1(episodes=5, timesteps=256, batch_size=64, gamma=0.999, lambda_=0.995, save_every='end', stage_name='stage',
                  seed=42, polyak=0.999, aug_intensity=0.0, repeat_action=1, load_full=False)\
        .run2(epochs=10)
I meet with this error: 
     NotImplementedError: Cannot convert a structure of tensors to a single tensor. Saw (<tf.Tensor 'distribution_lambda/distribution_lambda
_Beta/value/distribution_lambda_Beta/sample/Reshape:0' shape=(None, 2) dtype=float32>,........... 
I can't work out this problem, could you please help me?

**Comment by DADDYFUCKU** [comment]
I know this kind of error is about Tensorflow,  and I use the exact version which requirements.txt specifies.

**Comment by Luca96** [comment]
Try to install `tensorflow` 2.2.0 and `tensorflow-probability` 0.10.1

If it still complains, please provide the full error message.
